# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bed65f6301cea975b69384a600cf0b4a5f1b5ac8d2a013b059c431a7103710f861f139ed542e77a78427fc07d62377cb2604179849ac54c92fadcbee486aff8

test:
  secret_key_base: b15fe0a39454c7501331761f1577b63488ea07b55cb234713897491548a472e471814de3e34f66c3261ec907148b2710f21d2b03a561197e833776817f3041f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
